# Generated by Django 2.0.2 on 2018-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180313_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcing',
            name='rss_url',
            field=models.URLField(max_length=300),
        ),
    ]
