# Generated by Django 2.0.2 on 2018-03-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180315_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body_text', models.TextField()),
                ('companies', models.TextField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Sourcing')),
            ],
        ),
    ]
