# Generated by Django 2.0.2 on 2018-03-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180315_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='companies',
        ),
        migrations.AlterField(
            model_name='stories',
            name='body_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Sourcing'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
