# Generated by Django 2.0.2 on 2018-03-20 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0008_auto_20180315_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourcing',
            unique_together={('rss_url', 'created_by')},
        ),
    ]
