# Generated by Django 2.0.2 on 2018-04-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20180320_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='pub_date',
            field=models.DateTimeField(default='2018-04-11 12:10:20'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Sourcing'),
        ),
        migrations.AlterUniqueTogether(
            name='stories',
            unique_together={('url', 'source')},
        ),
    ]
